### ISSUE TITLE
Lot of errors trying to install Netdisco

### ISSUE THREAD

**Issue by lucdnb** [netdisco/netdisco#1228]
Hello everyone.
I'm trying to install Netdisco in my work, for use its features. But i'm having a lot of trouble to install it. Now, I have problems with SNMP libraries that i'm not able to know what I need to solve.

When I try to run "~/bin/netdisco-deploy":

>Can't load '/usr/local/lib64/perl5/auto/NetSNMP/default_store/default_store.so' for module NetSNMP::default_store: libnetsnmp.so.40: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 190.
 at /home/user/perl5/lib/perl5/x86_64-linux-thread-multi/SNMP.pm line 19.
Compilation failed in require at /home/user/perl5/lib/perl5/x86_64-linux-thread-multi/SNMP.pm line 19.
BEGIN failed--compilation aborted at /home/user/perl5/lib/perl5/x86_64-linux-thread-multi/SNMP.pm line 19.
Compilation failed in require at /home/user/perl5/lib/perl5/App/Netdisco/Configuration.pm line 24.
BEGIN failed--compilation aborted at /home/user/perl5/lib/perl5/App/Netdisco/Configuration.pm line 24.
Compilation failed in require at /home/user/perl5/lib/perl5/App/Netdisco.pm line 8.
BEGIN failed--compilation aborted at /home/user/perl5/lib/perl5/App/Netdisco.pm line 8.
Compilation failed in require at /home/user/bin/netdisco-deploy line 40.
BEGIN failed--compilation aborted at /home/user/bin/netdisco-deploy line 40.
I have some problems here. Some libraries I solved but this one I dont know how.

I'm working with a Rhel 7.9 server.

I had installed many others SNMP and perl-snmp libraries. Some ones worked but I always stop on other ones.

Can you guys help me with this?

**Comment by inphobia** [comment]
at first glance this seems that either you didn't install net-snmp-perl or it's not in your path, due to how intimate it is with net-snmp in general you can't use the cpan version, it has to be the os version.

please see:
https://metacpan.org/pod/App::Netdisco#Dependencies

**Comment by lucdnb** [comment]
Just one of this dependencies (net-snmp-perl) return the error `No package net-snmp-perl available.` 

But, I installed it mannualy. After that, some dependency errors are solved and this one is now stucking (as I mencioned):

> Can't load '/usr/local/lib64/perl5/auto/NetSNMP/default_store/default_store.so' for module NetSNMP::default_store:

Maybe the problem is the installation procedure is not finding where is this mannualy net-snmp-perl installation?

**Comment by kingtrw** [comment]
What is your environment (linux distribution/version) and are you using the container or the os native install?

**Comment by lucdnb** [comment]
Hello!
I'm glad to say, I solved all these problems and I have Netdisco full working right now.
My problem was because my Rhel server are not able to connect on extras repositories, by my work job security policies. So then all the snmp dependencies dont had be installed.

So, I had to install one by one mannualy. I had a lot of problems with that and another ones like update the Postgresql version and so on.

Thanks a lot for the responses. I am available to help others with Netdisco installation with the issues that I had before.
